export const SCIENCE_CAMERAS = [
  {
    id: "PH_LIVE_01",
    index: "PH-20",
    name: "PH-Live 活细胞相差镜",
    category: "光学显微",
    type: "science-camera",
    engine: "webgl-shader",
    family: "phase",
    summary: "灰蓝低饱和、透明样品边缘明暗光环、显微玻片质感。",
    recommended: "人物、宠物、食物、透明物、日常物体",
    tone: { exposure: 0.08, contrast: 1.08, gamma: 0.94, saturation: 0.45, blackLevel: -0.05 },
    analysis: { useLab: true, useSuperpixels: true, superpixelCount: 256, clusterCount: 6, useSaliency: true, useTexture: true, useEdges: true },
    regionMapping: { halo: ["edge", "texture", "saliency"], stain: ["luminance", "cluster"] },
    structure: { method: "dog-halo", amount: 0.42 },
    optics: { field: "microscope-circle", coverage: 0.84, vignette: 0.18, dust: 0.08, bloom: 0.04 },
    sensor: { readNoise: 0.012, shotNoise: 0.018, fixedPatternNoise: 0.002, hotPixels: 0 },
    frame: { showScale: false, metadata: "SIMULATED PHASE VIEW" },
    defaults: { title: "PH-Live", subtitle: "Live cell phase contrast look", meta: "SIMULATED VIEW" }
  },
  {
    id: "FL_DUO_01",
    index: "FL-Duo",
    name: "FL-Duo 绿紫双通道荧光镜",
    category: "荧光成像",
    type: "science-camera",
    engine: "webgl-shader",
    family: "fluorescence",
    summary: "黑场扣除、结构通道映射绿色、细节通道映射紫色，带 Bloom 与点状信号。",
    recommended: "人像轮廓、宠物、花束、树枝、夜景",
    tone: { exposure: -0.24, contrast: 1.28, gamma: 0.9, saturation: 1, blackLevel: 0.2 },
    analysis: { useLab: true, useSuperpixels: true, superpixelCount: 256, clusterCount: 6, useSaliency: true, useTexture: true, useEdges: true },
    regionMapping: {
      channelA: { source: ["smooth", "foreground"], strength: 0.86 },
      channelB: { source: ["detail", "edge"], strength: 0.72 },
      channelC: { source: ["highlight", "material"], strength: 0.28 }
    },
    channels: [
      { id: "A", source: "structure", color: "#42FF78", intensity: 0.86, threshold: 0.2 },
      { id: "B", source: "detail", color: "#C44BFF", intensity: 0.72, threshold: 0.28 }
    ],
    structure: { method: "dual-mask", amount: 0.35 },
    optics: { bloom: 0.2, vignette: 0.1, chromaticShift: 0.002, dust: 0.03 },
    sensor: { readNoise: 0.015, shotNoise: 0.04, fixedPatternNoise: 0.004, hotPixels: 0.001 },
    frame: { showScale: false, metadata: "VISUAL PSEUDO-COLOR / NO CALIBRATION" },
    defaults: { title: "FL-Duo", subtitle: "Channel A Green / Channel B Violet", meta: "VISUAL PSEUDO-COLOR" }
  },
  {
    id: "SEM_CARBON_01",
    index: "SEM-C",
    name: "SEM-Carbon 扫描电子显微镜",
    category: "电子显微",
    type: "science-camera",
    engine: "webgl-shader",
    family: "electron",
    summary: "冷灰黑白、高频纹理增强、微弱扫描纹理和电子显微镜参数栏。",
    recommended: "建筑、机械、毛发、树皮、布料、食物表面",
    tone: { exposure: -0.06, contrast: 1.55, gamma: 0.88, saturation: 0, blackLevel: 0.08 },
    analysis: { useLab: true, useSuperpixels: true, superpixelCount: 256, clusterCount: 6, useSaliency: false, useTexture: true, useEdges: true },
    regionMapping: { material: ["lab", "texture", "edge"], localContrast: ["edge", "texture"], surface: ["luminance", "direction"] },
    structure: { method: "multi-scale-surface", amount: 0.72 },
    optics: { vignette: 0.16, scanline: 0.05, bloom: 0.03 },
    sensor: { readNoise: 0.025, shotNoise: 0.018, fixedPatternNoise: 0.01, hotPixels: 0.0003 },
    frame: { showScale: false, metadata: "SEM-C  HV 5.0kV  WD 8.2mm  SIMULATED SCALE" },
    defaults: { title: "SEM-Carbon", subtitle: "HV 5.0kV  WD 8.2mm  SE", meta: "SIMULATED SCALE" }
  },
  {
    id: "DIFFUSION_STAIN_01",
    index: "DS-01",
    name: "Diffusion-Stain 晕染染色",
    category: "数据伪彩",
    type: "science-camera",
    engine: "webgl-shader",
    family: "stain",
    summary: "保留亮度结构，用粉蓝/绿紫染液感做区域扩散和玻片质感。",
    recommended: "花朵、食物、衣物、玻璃、晚霞、人像",
    tone: { exposure: 0.06, contrast: 1.02, gamma: 0.98, saturation: 1.12, blackLevel: -0.02 },
    analysis: { useLab: true, useSuperpixels: true, superpixelCount: 256, clusterCount: 6, useSaliency: true, useTexture: true, useEdges: true },
    regionMapping: { stainStrength: ["color-cluster", "texture", "saliency"], penetration: ["luminance", "edge", "texture"] },
    stain: { primary: "#d980c5", secondary: "#6dd6e8", diffusion: 0.42 },
    structure: { method: "soft-edge", amount: 0.18 },
    optics: { bloom: 0.08, vignette: 0.06, dust: 0.04 },
    sensor: { readNoise: 0.008, shotNoise: 0.012, fixedPatternNoise: 0.001, hotPixels: 0 },
    frame: { showScale: false, metadata: "VISUAL STAIN MAP" },
    defaults: { title: "Diffusion-Stain", subtitle: "Soft tissue stain look", meta: "VISUAL STAIN MAP" }
  },
  {
    id: "DIC_RELIEF_01",
    index: "DIC-R",
    name: "DIC-Relief 微分浮雕镜",
    category: "光学显微",
    type: "science-camera",
    engine: "webgl-shader",
    family: "phase",
    summary: "方向梯度浮雕、青灰金属底、局部边缘一侧亮一侧暗。",
    tone: { exposure: 0.02, contrast: 1.2, gamma: 0.9, saturation: 0.28, blackLevel: -0.02 },
    structure: { method: "directional-relief", amount: 0.68 },
    optics: { field: "microscope-circle", coverage: 0.86, vignette: 0.1, bloom: 0.02, dust: 0.03 },
    sensor: { readNoise: 0.01, shotNoise: 0.012, fixedPatternNoise: 0.002, hotPixels: 0 },
    frame: { showScale: false, metadata: "DIC RELIEF / SIMULATED" },
    defaults: { title: "DIC-Relief", subtitle: "Directional relief contrast", meta: "SIMULATED VIEW" }
  },
  {
    id: "POL_CRYSTAL_01",
    index: "POL-X",
    name: "POL-Crystal 偏振晶体镜",
    category: "数据伪彩",
    type: "science-camera",
    engine: "webgl-shader",
    family: "stain",
    summary: "深色背景、青紫橙虹彩、纹理方向驱动的偏振晶体感。",
    tone: { exposure: -0.04, contrast: 1.22, gamma: 0.86, saturation: 1.35, blackLevel: 0.08 },
    stain: { primary: "#ff9b32", secondary: "#30f0ff", diffusion: 0.5 },
    structure: { method: "gradient-iridescence", amount: 0.42 },
    optics: { bloom: 0.14, vignette: 0.18, chromaticShift: 0.003, dust: 0.01 },
    sensor: { readNoise: 0.008, shotNoise: 0.012, fixedPatternNoise: 0.001, hotPixels: 0.0002 },
    frame: { showScale: false, metadata: "POLARIZED PSEUDO-COLOR" },
    defaults: { title: "POL-Crystal", subtitle: "Cross-polarized iridescence", meta: "VISUAL PSEUDO-COLOR" }
  },
  {
    id: "PIXEL_SAMPLE_01",
    index: "PX-S",
    name: "Pixel-Sample 低像素样本",
    category: "数据伪彩",
    type: "science-camera",
    engine: "canvas-analysis",
    family: "stain",
    summary: "色块量化、区域分割和低像素组织切片感。",
    tone: { exposure: 0.02, contrast: 1.12, gamma: 0.96, saturation: 1.22, blackLevel: 0 },
    stain: { primary: "#7bdff2", secondary: "#f2b5d4", diffusion: 0.22 },
    structure: { method: "quantized-blocks", amount: 0.34 },
    optics: { bloom: 0.02, vignette: 0.06, dust: 0.01 },
    sensor: { readNoise: 0.006, shotNoise: 0.01, fixedPatternNoise: 0, hotPixels: 0 },
    frame: { showScale: false, metadata: "COLOR CLUSTER MAP / VISUAL" },
    defaults: { title: "Pixel-Sample", subtitle: "Segmented color blocks", meta: "VISUAL CLUSTER MAP" }
  },
  {
    id: "BRIGHTFIELD_40X_01",
    index: "BF-40",
    name: "Brightfield 40x 明场显微镜",
    category: "光学显微",
    type: "science-camera",
    engine: "webgl-shader",
    family: "phase",
    summary: "亮背景、自然低饱和样本色、圆形视野和轻微边缘失焦。",
    tone: { exposure: 0.12, contrast: 0.98, gamma: 0.96, saturation: 0.78, blackLevel: -0.08 },
    structure: { method: "soft-brightfield", amount: 0.2 },
    optics: { field: "microscope-circle", coverage: 0.88, vignette: 0.14, bloom: 0.02, dust: 0.05 },
    sensor: { readNoise: 0.007, shotNoise: 0.012, fixedPatternNoise: 0.001, hotPixels: 0 },
    frame: { showScale: false, metadata: "BRIGHTFIELD LOOK / VISUAL SCALE" },
    defaults: { title: "Brightfield 40x", subtitle: "Objective 40x / Eyepiece 10x", meta: "VISUAL SCALE" }
  },
  {
    id: "DARKFIELD_SPARK_01",
    index: "DF-01",
    name: "Darkfield 暗场显微镜",
    category: "光学显微",
    type: "science-camera",
    engine: "webgl-shader",
    family: "fluorescence",
    summary: "黑场、边缘亮散射、微颗粒和蓝白高反差信号。",
    tone: { exposure: -0.18, contrast: 1.55, gamma: 0.82, saturation: 1.15, blackLevel: 0.28 },
    channels: [
      { id: "A", color: "#d8f7ff", intensity: 0.74, threshold: 0.24 },
      { id: "B", color: "#74a9ff", intensity: 0.48, threshold: 0.32 }
    ],
    structure: { method: "darkfield-edge", amount: 0.48 },
    optics: { bloom: 0.22, vignette: 0.16, dust: 0.02 },
    sensor: { readNoise: 0.018, shotNoise: 0.04, fixedPatternNoise: 0.004, hotPixels: 0.001 },
    frame: { showScale: false, metadata: "DARKFIELD SCATTER / SIMULATED" },
    defaults: { title: "Darkfield", subtitle: "Scattering edge contrast", meta: "SIMULATED VIEW" }
  },
  {
    id: "CONFOCAL_RGB_01",
    index: "CF-Z",
    name: "Confocal RGB 共聚焦层扫",
    category: "荧光成像",
    type: "science-camera",
    engine: "webgl-shader",
    family: "fluorescence",
    summary: "黑背景、多通道伪彩层扫、轻微通道错位和 Z-stack 融合感。",
    tone: { exposure: -0.2, contrast: 1.42, gamma: 0.86, saturation: 1.25, blackLevel: 0.24 },
    channels: [
      { id: "A", color: "#00ff7a", intensity: 0.76, threshold: 0.18 },
      { id: "B", color: "#c44bff", intensity: 0.7, threshold: 0.26 }
    ],
    structure: { method: "zstack-merge", amount: 0.44 },
    optics: { bloom: 0.24, vignette: 0.12, chromaticShift: 0.004, dust: 0.02 },
    sensor: { readNoise: 0.016, shotNoise: 0.045, fixedPatternNoise: 0.004, hotPixels: 0.0012 },
    frame: { showScale: false, metadata: "RGB CONFOCAL MERGE / VISUAL" },
    defaults: { title: "Confocal RGB", subtitle: "CH1 Green / CH2 Magenta / CH3 Blue", meta: "VISUAL MERGE" }
  },
  {
    id: "GFP_SINGLE_01",
    index: "GFP",
    name: "GFP 单通道绿荧光",
    category: "荧光成像",
    type: "science-camera",
    engine: "webgl-shader",
    family: "fluorescence",
    summary: "纯黑背景、绿色信号、高光 Bloom 和少量热像素。",
    tone: { exposure: -0.18, contrast: 1.5, gamma: 0.88, saturation: 1.15, blackLevel: 0.26 },
    channels: [
      { id: "A", color: "#22ff66", intensity: 0.9, threshold: 0.2 },
      { id: "B", color: "#77ffaa", intensity: 0.18, threshold: 0.4 }
    ],
    structure: { method: "single-channel", amount: 0.28 },
    optics: { bloom: 0.24, vignette: 0.1, dust: 0.015 },
    sensor: { readNoise: 0.018, shotNoise: 0.048, fixedPatternNoise: 0.004, hotPixels: 0.001 },
    frame: { showScale: false, metadata: "GFP 488nm / VISUAL PSEUDO-COLOR" },
    defaults: { title: "GFP", subtitle: "Single channel green fluorescence", meta: "VISUAL PSEUDO-COLOR" }
  },
  {
    id: "RFP_SINGLE_01",
    index: "RFP",
    name: "RFP 单通道红荧光",
    category: "荧光成像",
    type: "science-camera",
    engine: "webgl-shader",
    family: "fluorescence",
    summary: "红色单通道、干净黑场、边缘信号强化。",
    tone: { exposure: -0.18, contrast: 1.5, gamma: 0.9, saturation: 1.12, blackLevel: 0.28 },
    channels: [
      { id: "A", color: "#ff3b30", intensity: 0.86, threshold: 0.22 },
      { id: "B", color: "#ff9a8d", intensity: 0.2, threshold: 0.4 }
    ],
    structure: { method: "single-channel", amount: 0.3 },
    optics: { bloom: 0.22, vignette: 0.12, dust: 0.015 },
    sensor: { readNoise: 0.018, shotNoise: 0.044, fixedPatternNoise: 0.004, hotPixels: 0.001 },
    frame: { showScale: false, metadata: "RFP 561nm / VISUAL PSEUDO-COLOR" },
    defaults: { title: "RFP", subtitle: "Single channel red fluorescence", meta: "VISUAL PSEUDO-COLOR" }
  },
  {
    id: "DAPI_NUCLEI_01",
    index: "DAPI",
    name: "DAPI 蓝色细胞核风格",
    category: "荧光成像",
    type: "science-camera",
    engine: "webgl-shader",
    family: "fluorescence",
    summary: "深黑背景、蓝色核样点状信号、弱边缘光。",
    tone: { exposure: -0.2, contrast: 1.48, gamma: 0.86, saturation: 1.18, blackLevel: 0.28 },
    channels: [
      { id: "A", color: "#3d7dff", intensity: 0.78, threshold: 0.24 },
      { id: "B", color: "#b8d3ff", intensity: 0.36, threshold: 0.34 }
    ],
    structure: { method: "nuclei-points", amount: 0.38 },
    optics: { bloom: 0.2, vignette: 0.13, dust: 0.01 },
    sensor: { readNoise: 0.016, shotNoise: 0.042, fixedPatternNoise: 0.004, hotPixels: 0.001 },
    frame: { showScale: false, metadata: "DAPI-LIKE / VISUAL PSEUDO-COLOR" },
    defaults: { title: "DAPI-like", subtitle: "Blue nuclei style", meta: "VISUAL PSEUDO-COLOR" }
  },
  {
    id: "HE_TISSUE_01",
    index: "HE",
    name: "H&E-like 组织染色",
    category: "光学显微",
    type: "science-camera",
    engine: "webgl-shader",
    family: "stain",
    summary: "粉蓝病理染色、白底玻片、局部组织层次。",
    tone: { exposure: 0.14, contrast: 0.98, gamma: 0.98, saturation: 0.92, blackLevel: -0.04 },
    stain: { primary: "#d78ac8", secondary: "#7fb7df", diffusion: 0.34 },
    structure: { method: "tissue-stain", amount: 0.24 },
    optics: { bloom: 0.04, vignette: 0.06, dust: 0.06 },
    sensor: { readNoise: 0.007, shotNoise: 0.012, fixedPatternNoise: 0.001, hotPixels: 0 },
    frame: { showScale: false, metadata: "H&E-LIKE VISUAL STAIN" },
    defaults: { title: "H&E-like", subtitle: "Pseudo tissue stain", meta: "VISUAL STAIN" }
  },
  {
    id: "TEM_SLICE_01",
    index: "TEM",
    name: "TEM 透射电镜薄切片",
    category: "电子显微",
    type: "science-camera",
    engine: "webgl-shader",
    family: "electron",
    summary: "灰白低饱和、薄切片内部层次、低噪超微结构感。",
    tone: { exposure: 0.02, contrast: 1.25, gamma: 0.92, saturation: 0, blackLevel: -0.02 },
    structure: { method: "ultrastructure", amount: 0.46 },
    optics: { vignette: 0.08, scanline: 0.018, bloom: 0.01 },
    sensor: { readNoise: 0.014, shotNoise: 0.014, fixedPatternNoise: 0.004, hotPixels: 0.0001 },
    frame: { showScale: false, metadata: "TEM-LIKE ULTRASTRUCTURE / SIMULATED" },
    defaults: { title: "TEM Slice", subtitle: "Low contrast ultrastructure", meta: "SIMULATED SCALE" }
  },
  {
    id: "CRYO_PARTICLE_01",
    index: "CRYO",
    name: "Cryo 风格颗粒图",
    category: "电子显微",
    type: "science-camera",
    engine: "webgl-shader",
    family: "electron",
    summary: "低对比冷冻电镜颗粒板、柔灰背景和微弱随机颗粒。",
    tone: { exposure: -0.02, contrast: 1.12, gamma: 1.02, saturation: 0, blackLevel: 0.02 },
    structure: { method: "particle-field", amount: 0.32 },
    optics: { vignette: 0.04, scanline: 0.012, bloom: 0 },
    sensor: { readNoise: 0.028, shotNoise: 0.016, fixedPatternNoise: 0.006, hotPixels: 0.0002 },
    frame: { showScale: false, metadata: "CRYO PARTICLE LOOK / SIMULATED" },
    defaults: { title: "Cryo Particle", subtitle: "Low contrast particle field", meta: "SIMULATED VIEW" }
  },
  {
    id: "CCD_90S_01",
    index: "CCD-98",
    name: "90s 实验室 CCD",
    category: "科学档案",
    type: "science-camera",
    engine: "canvas-analysis",
    family: "electron",
    summary: "旧 CCD 数字噪声、压缩感、仪器记录色偏。",
    tone: { exposure: 0.01, contrast: 1.08, gamma: 1.05, saturation: 0.72, blackLevel: 0.04 },
    structure: { method: "ccd-digital", amount: 0.2 },
    optics: { vignette: 0.12, scanline: 0.035, bloom: 0.015 },
    sensor: { readNoise: 0.045, shotNoise: 0.025, fixedPatternNoise: 0.018, hotPixels: 0.0008 },
    frame: { showScale: false, metadata: "LAB CCD 1998 / SIMULATED" },
    defaults: { title: "CCD-98", subtitle: "Laboratory digital camera", meta: "SIMULATED ARCHIVE" }
  },
  {
    id: "INSTRUMENT_SCREEN_01",
    index: "LCD",
    name: "仪器屏幕风格",
    category: "科学档案",
    type: "science-camera",
    engine: "canvas-analysis",
    family: "fluorescence",
    summary: "黑底仪器屏幕、数字扫描线、绿色终端式信号。",
    tone: { exposure: -0.14, contrast: 1.34, gamma: 0.92, saturation: 0.96, blackLevel: 0.22 },
    channels: [
      { id: "A", color: "#70e1bf", intensity: 0.72, threshold: 0.18 },
      { id: "B", color: "#d7f7eb", intensity: 0.24, threshold: 0.35 }
    ],
    structure: { method: "screen-signal", amount: 0.28 },
    optics: { bloom: 0.12, vignette: 0.18, scanline: 0.08, dust: 0 },
    sensor: { readNoise: 0.012, shotNoise: 0.02, fixedPatternNoise: 0.012, hotPixels: 0.0003 },
    frame: { showScale: false, metadata: "INSTRUMENT DISPLAY / SIMULATED" },
    defaults: { title: "Instrument Screen", subtitle: "Pseudo signal display", meta: "SIMULATED DATA VIEW" }
  },
  {
    id: "ARCHIVE_SCAN_01",
    index: "ARC",
    name: "老式扫描档案",
    category: "科学档案",
    type: "science-camera",
    engine: "canvas-analysis",
    family: "phase",
    summary: "米白纸感、低饱和扫描、轻微压痕和档案灰。",
    tone: { exposure: 0.08, contrast: 0.9, gamma: 1.05, saturation: 0.45, blackLevel: -0.04 },
    structure: { method: "archive-scan", amount: 0.16 },
    optics: { vignette: 0.08, dust: 0.08, bloom: 0 },
    sensor: { readNoise: 0.018, shotNoise: 0.012, fixedPatternNoise: 0.008, hotPixels: 0 },
    frame: { showScale: false, metadata: "SCANNED SCIENTIFIC ARCHIVE" },
    defaults: { title: "Archive Scan", subtitle: "Old laboratory record", meta: "SCIENTIFIC ARCHIVE" }
  },
  {
    id: "HEATMAP_VISUAL_01",
    index: "HM",
    name: "Visual Heatmap 视觉热力图",
    category: "抽象数据化",
    type: "science-camera",
    engine: "webgl-shader",
    family: "stain",
    summary: "由亮度、边缘和颜色密度派生的视觉伪热图。",
    tone: { exposure: -0.02, contrast: 1.18, gamma: 0.9, saturation: 1.25, blackLevel: 0.02 },
    stain: { primary: "#2532ff", secondary: "#ffcf33", diffusion: 0.5 },
    structure: { method: "pseudo-heatmap", amount: 0.36 },
    optics: { bloom: 0.08, vignette: 0.05, dust: 0 },
    sensor: { readNoise: 0.005, shotNoise: 0.008, fixedPatternNoise: 0, hotPixels: 0 },
    frame: { showScale: false, metadata: "VISUAL HEATMAP / NOT MEASUREMENT" },
    defaults: { title: "Visual Heatmap", subtitle: "Derived intensity map", meta: "PSEUDO HEATMAP" }
  },
  {
    id: "MODEL_DIAGRAM_01",
    index: "MDL",
    name: "Model Diagram 模型图风格",
    category: "抽象数据化",
    type: "science-camera",
    engine: "canvas-analysis",
    family: "stain",
    summary: "将图像抽象为节点、结构和模型示意图氛围。",
    tone: { exposure: -0.04, contrast: 1.1, gamma: 0.94, saturation: 1.05, blackLevel: 0.04 },
    stain: { primary: "#70e1bf", secondary: "#8c6cff", diffusion: 0.28 },
    structure: { method: "model-diagram", amount: 0.22 },
    optics: { bloom: 0.08, vignette: 0.12, dust: 0 },
    sensor: { readNoise: 0.006, shotNoise: 0.006, fixedPatternNoise: 0.002, hotPixels: 0 },
    frame: { showScale: false, metadata: "CONCEPTUAL MODEL / VISUAL" },
    defaults: { title: "Model Diagram", subtitle: "Image-derived conceptual style", meta: "VISUAL MODEL" }
  }
];
